
stages:
  - build

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  image: ${CI_REGISTRY}/public/java-runtime:11
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - mkdir -p ~/.gradle
    - echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
    - chmod +x gradlew
    - bash ./gradlew clean
  script:
    - bash ./gradlew build
