rootProject.name = "EasyConnectKt"
include("bom")
include("net-api")
include("net-cli")
include("net-core")
include("net-crypto")
include("net-proto:net-proto-tcp")
include("net-proto:net-proto-udp")
include("net-proto:net-proto-websocket")
include("net-plugin:net-plugin-http-route")
include("net-plugin:net-plugin-service-context")
include("net-plugin:net-plugin-nat")
include("net-plugin:net-plugin-cert-manager")
include("net-plugin:net-plugin-web-panel")
